[project]
name = "nostr-threshold"
version = "0.1.0"  # Explicit version added
description = "Threshold signing for Nostr"
requires-python = ">=3.8"
dependencies = [
    "nostr-sdk>=0.8",
    "python-dotenv",
]

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"